services:
  connectors:
    build: .
    image: data-connector-app-poc
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_HOST: host.docker.internal
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs:ro
    ports:
      - "3000:3000"
    command: ["node", "src/cli.js", "help"]
